name: MultiverseHardcore
version: 1.0.3
main: life.lluis.multiversehardcore.MultiverseHardcore
commands:
  mvhc:
    description: Main MultiverseHardcore command. Options = { create, makehc, player, world, list, version }
    usage: /<command> [option]
    aliases: [ ]
  mvhchelp:
    description: Displays MultiverseHardcore options.
    usage: /<command>
    aliases: [ ]